#! /bin/sh
rm *.xml
wget http://www.data.jma.go.jp/developer/xml/feed/regular.xml
wget http://www.data.jma.go.jp/developer/xml/feed/regular_l.xml
file=`cat regular.xml | grep "id" | grep "G50_280000" | sed -e "s/<id>//g" | sed -e "s/<\/id>//g"`
wget ${file}
file=`cat regular.xml | grep "id" | grep "D50_280000" | sed -e "s/<id>//g" | sed -e "s/<\/id>//g"`
wget ${file}
file=`cat regular.xml | grep "id" | grep "W50_280000" | sed -e "s/<id>//g" | sed -e "s/<\/id>//g"`
if [ ${#file} -gt 0 ]; then
  wget ${file}
else
  file=`cat regular_l.xml | grep "id" | grep "W50_280000" | sed -e "s/<id>//g" | sed -e "s/<\/id>//g" | head -n 1`
  wget ${file}
fi

